выполнила задания и 3 занятия
js-tasks-ru/jsbasic-20240321_oksunny pull request #3
Opened 2024-03-31 10:16 UTC by ooksunny

2024-03-31 10:17 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2024-03-31 10:43 UTC, SinimaWath requested changes

2024-03-31 10:43 UTC, SinimaWath commented on 0-module/1-task/index.js
> +alert(sum())
Из файла надо убрать все лишнее, кроме решения задачи. Дава уберем alert

2024-03-31 10:43 UTC, SinimaWath commented on 1-module/1-task/index.js
> +alert(factorial())
Из файла надо убрать все лишнее, кроме решения задачи. Дава уберем alert

2024-03-31 10:43 UTC, SinimaWath commented on 1-module/4-task/index.js
> +alert(checkSpam())
Из файла надо убрать все лишнее, кроме решения задачи. Дава уберем alert

2024-03-31 10:43 UTC, SinimaWath commented on 2-module/1-task/index.js
> +sumSalary(salaries);
Из файла надо убрать все лишнее, кроме решения задачи. Дава уберем sumSalary

2024-03-31 10:43 UTC, SinimaWath commented on 2-module/1-task/index.js
> +}
Из файла надо убрать все лишнее, кроме решения задачи. Дава уберем salaries

2024-04-01 12:56 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-01 15:59 UTC, SinimaWath reviewed
Давай поправим все замечания, которые есть выше

2024-04-01 18:25 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-01 19:01 UTC, SinimaWath approved these changes

2024-04-01 19:01 UTC, merged